"use client";

import Link from "next/link";
import { ChangeEvent, useCallback, useEffect, useState } from "react";

type Model={id:string;code:string;name:string;status:string;product:{code:string;name:string}};
type Asset={id:string;asset_type:string;file_name:string;mime_type:string;size_bytes:number|null;sha256:string|null;visibility:string};
const API=process.env.NEXT_PUBLIC_ALSVID_API_BASE_URL||"";

export default function ProductAssets({code}:{code:string}) {
  const [model,setModel]=useState<Model|null>(null),[assets,setAssets]=useState<Asset[]>([]),[assetType,setAssetType]=useState("PRODUCT_IMAGE"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setMessage("");const response=await fetch(API+"/api/v1/product-center/models",{credentials:"include",cache:"no-store"});const models:Model[]=await response.json();if(!response.ok)throw new Error("Unable to load ALSVID models");const current=models.find(item=>item.product.code===code||item.code===code);if(!current)throw new Error("ALSVID model not found");setModel(current);const assetResponse=await fetch(API+`/api/v1/assets?owner_type=MODEL&owner_id=${encodeURIComponent(current.id)}`,{credentials:"include",cache:"no-store"});const assetData=await assetResponse.json();if(!assetResponse.ok)throw new Error(assetData.detail||"Unable to load assets");setAssets(assetData)},[code]);
  useEffect(()=>{void load().catch((error:unknown)=>setMessage(error instanceof Error?error.message:"Unable to load product"))},[load]);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file||!model)return;setBusy(true);setMessage("");try{const ticketResponse=await fetch(API+"/api/v1/assets/upload-ticket",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({owner_type:"MODEL",owner_id:model.id,asset_type:assetType,visibility:"INTERNAL",file_name:file.name,mime_type:file.type||"application/octet-stream"})});const ticket=await ticketResponse.json();if(!ticketResponse.ok)throw new Error(ticket.detail||"Unable to create upload ticket");const uploadResponse=await fetch(ticket.upload_url,{method:ticket.method||"PUT",headers:ticket.headers||{"Content-Type":file.type||"application/octet-stream"},body:file});if(!uploadResponse.ok)throw new Error("Object storage upload failed");const finalizeResponse=await fetch(API+"/api/v1/assets/finalize",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({owner_type:"MODEL",owner_id:model.id,asset_type:assetType,visibility:"INTERNAL",file_name:file.name,mime_type:file.type||"application/octet-stream",storage_key:ticket.storage_key,size_bytes:file.size})});const finalized=await finalizeResponse.json();if(!finalizeResponse.ok)throw new Error(finalized.detail||"Unable to finalize asset");await load()}catch(error){setMessage(error instanceof Error?error.message:"Upload failed")}finally{setBusy(false);event.target.value=""}}
  return <main style={{maxWidth:1080,margin:"0 auto",padding:"40px 24px"}}><Link href="/" style={{color:"#667085",textDecoration:"none"}}>← ALSVID home</Link><header style={{margin:"28px 0 20px"}}><p style={{color:"#667085",margin:0}}>ALSVID · Product Center</p><h1 style={{margin:"6px 0 0"}}>{model?.product.name||code}</h1><p style={{color:"#667085"}}>{model?`${model.code} · ${model.status}`:"Loading…"}</p></header><section style={cardStyle}><div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap"}}><select value={assetType} onChange={event=>setAssetType(event.target.value)} style={inputStyle}><option value="PRODUCT_IMAGE">Product image</option><option value="DETAIL_IMAGE">Detail image</option><option value="EXPLODED_VIEW">Exploded view</option><option value="MANUAL">Manual</option><option value="SERVICE_DOC">Service document</option><option value="DEALER_DOC">Dealer document</option><option value="MODEL_3D">3D model</option><option value="VIDEO">Video</option></select><label style={buttonStyle}>{busy?"Uploading…":"Upload asset"}<input type="file" disabled={busy} onChange={upload} style={{display:"none"}}/></label>{model&&<Link href={`/models/${model.id}/bom`} style={{color:"#175cd3",fontWeight:600}}>View BOM →</Link>}</div>{message&&<p role="alert" style={{color:"#b42318"}}>{message}</p>}<table style={{width:"100%",borderCollapse:"collapse",marginTop:20}}><thead><tr>{["File","Type","Size","SHA-256"].map(label=><th key={label} style={thStyle}>{label}</th>)}</tr></thead><tbody>{assets.map(asset=><tr key={asset.id}><td style={tdStyle}>{asset.file_name}</td><td style={tdStyle}>{asset.asset_type}</td><td style={tdStyle}>{asset.size_bytes??"—"}</td><td style={tdStyle}>{asset.sha256||"—"}</td></tr>)}</tbody></table></section></main>;
}
const cardStyle={padding:22,background:"#fff",border:"1px solid #e5e7eb",borderRadius:16},buttonStyle={display:"inline-block",borderRadius:9,padding:"10px 16px",background:"#175cd3",color:"#fff",fontWeight:600,cursor:"pointer"},inputStyle={padding:"9px 12px",border:"1px solid #d0d5dd",borderRadius:8,font:"inherit"},thStyle={padding:"10px 12px",color:"#667085",fontSize:12,textAlign:"left" as const,borderBottom:"1px solid #e5e7eb"},tdStyle={padding:"12px",borderBottom:"1px solid #f0f1f3",fontSize:13};
